### PR TITLE
d3-request typings

### PR DESCRIPTION
**Pull request by Ledragon**
Hi,
I worked on the `d3-request` API, as per issue #44. Let me know this is OK, or if something is to be changed.

### CODE REVIEW

**Comment by tomwanzek** [comment]
Thanks for the PR, I will look over it later today and see what, if anything, comes to mind before merging.

I am currently cleaning up the d3-collection and d3-force. I will comment back to your initial issue/question related to formalizing the contribution process and the roadmap to get the definitions accessible through the 'traditional' definitions acquisitions channels for production use.

I did some more digging over the past couple of days related to @types.

**Comment by Ledragon** [comment]
Thanks for the feedback. No rush though, I already found some mistakes while writing tests, meaning that additional changes are coming.

**Comment by tomwanzek** [comment]
Thanks for the heads-up.

**Comment by tomwanzek** [comment]
I had a first glance over the PR. First of all, thanks. I am going to be offline for a few hours, I have a few minor suggestions for the test file and will mark them up when I am back on.

E. g. when checking the return types of methods/function, I tend to type the variable to assign to. This way the shape test fails, if one alters the definition later on accidentally. I do the same with re-assigning chainable methods to the originating object.

There are a couple of items I wanted to check against the API i.p. related to the event listeners' argument lists. As I usually use D3 with Angular, I tended to handle REST API calls through Angular, so it needs some quick brushing up on my part w.r.t. d3-request/response handling.

**Comment by Ledragon** [comment]
Thanks for the reply, I upgraded the tests accordingly, and completed them.

**Comment by tomwanzek** [comment]
**d3-request**
A couple of things that jumped out at me as questions:

(1) The usage of the generics `T` and `U`:
- Would it be preferable from a cognitive cue perspective to name them more explicitly, e.g. `RequestData`, `ResponseData`?
- There seems to be an inconsistency in usage that could be confusing: the `Request.response(...)` defintion uses the the generic `T`, but semantically elsewhere `U` is used, as it refers to the return data being extracted.

(2) For the event handler registered with `on`:
- could you double check, whether the signatures should be separated out, e.g. the `error` listener is passed in `error: any` and response data is undefined. However, e.g. for the `load` event handler there seems to be a contradiction in the API docs. The example under [request.send(...)](https://github.com/d3/d3-request#request_send) is called with `error` null and the reponse data as the second argument. But the `on(...)` documentation and the code in request.js seem to indicate it is just one data argument with the reponse data? Could be an error in the documentation example?
- in either case there should also be an `| string` following the string literals with the event types. This is done to register multiple listeners, e. g. `load.custom` in line with how _d3-dispatch_ works.

**d3-geo**:
Could you split the d3-geo work into a separate PR? Should make it easier to manage the PRs by module, when they are not inherently related changes.

**Comment by Ledragon** [comment]
**d3-request**
(1) The usage of the generics `T` and `U`: C# background, victim of my habits...
- Switched to `RequestType` and `ResponseType` for clarity
- `Request.Response` was indeed wrong, I corrected it together with the new names

(2) For the event handler registered with `on`:
- Thing are a  bit odd between registering to the `load` event and using a callback in the `send` method, but I think things are correct. In `request.js`, line 40, the `load` listener is called with a single argument, `result`. On line 115, when a callback function is provided to `send`, the request registers a listener to the `load` event, passing a single argument, the result of the xhr request, that calls the callback method using that result as the second argument, and setting the error to null. I added null as possible argument type for both arguments of the callback function.
- `| string` added as potential type of event

**d3-geo**
My bad, I am not yet used to everything following up to the PR, and as I work as a pig, I didn't branch for the geo types. I removed these from the `master` branch, and created a branch for `d3-geo`.

**Comment by tomwanzek** [comment]
Thanks a lot. I am going to merge it and if there are any additional changes I will add any reasoning to the issues thread for the d3-request definitions. I will add a header comment to each of the files comparable to the one in the other defs/tetst. As I did with the ones I drew up. I will leave the original two definitions authors listed. Instead of myself, I will list your reference info as the additional author.

Hope this is alright with you.

**Comment by Ledragon** [comment]
Sound perfect for me, thanks for the feedback.

**Pull request merged**
