### PR TITLE
D3 geo

### PR DESCRIPTION
**Pull request by Ledragon**
Definitions and tests of `d3-geo` module.
#50 #51

### CODE REVIEW

**Comment by tomwanzek** [comment]
Thanks, I will continue looking at this version and add any new comments/questions here.

Let's just say you picked quite a task with this one. Have to sink my teeth into the API doc and code as well to add more value :smile:. I am on it though...

**Comment by tomwanzek** [comment]
Here are the first couple of things that jumped out at me:
1. Housekeeping: there is an edit to `Gruntfile.js` that should no longer be required, since **typings** is out now. Instead, please add the `/// <reference types="geojson" />`  directive. It is referred to as the official pattern for consuming globals (see [here](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Library%20Structures.md#dependencies-on-global-libraries)). (I guess the only reason the compilation does not fail without it, is the way the GeoJSON def is currently written. But anyway it does not hurt to add it. So if GeoJSON gets rewritten for TS2, either we can still consume the global or it becomes a proper `import`)
2. There seems to be somewhat unfortunate wording in the API Doc for the _spherical math_ functions. Wherever a function in this section accepts a `feature` argument, it actually supports all of the following: any valid `GeometryObject`, `GeometryCollection`, `Feature` or `FeatureCollection`. It also accepts (by extension of the GeoJSON spec a quasi-`GeometryObject` for a sphere, which is mentioned elsewhere in the API Doc as `{ type: 'Sphere' }` and does not have a `coordinates property. It is also included in the module tests. So, these alternative signatures should be added together with the corresponding shape tests.

I'll let you know, if anything else comes up as I read on and look at the TODOs you have flagged.

**Comment by tomwanzek** [comment]
As for the `GeoCircleGenerator` and the TODO on it, I would lean towards the pattern I applied to `Symbol` in **d3-shape**:

```
export interface GeoCircleGenerator<This, Datum> {
    (this: This, d?: Datum, ...args: any[]): GeoJSON.Polygon;
    center(): (this: This, d?: Datum, ...args: any[]) => [number, number];
    center(center: [number, number]): this;
    center(center: (this: This, d?: Datum, ...args: any[]) => number): this;
...
}
```

This would go hand in hand with three functions to create a new `GeoCircleGenerator`:

```
export function geoCircle(): GeoCircleGenerator<any, any>;
export function geoCircle<Datum>(): GeoCircleGenerator<any, Datum>;
export function geoCircle<This, Datum>(): GeoCircleGenerator<This, Datum>;
```

A couple of additional notes:
- all the getters, e.g.`center()`, return an accessor function (never a value like [number, number]). Internally, Mike converts constants being passed into the setter into a _constant return value function_
- the generator invokes the accessors with the `this` context in which the GeoCircleGenerator function itself gets invoked. Typing the `this` argument as a generic allows one to control fairly sophisticated patterns. For an extreme example see the test file `d3-shape-test.ts` starting at line 957 (i.e. the `class Symbolizer` example).
- Whenever the setter signatures are _exclusive_, e.g. constant vs accessor function, it might be preferable to separate them rather than using a union type. Makes it easier to add more concise JSDoc comments later on as well

**Comment by Ledragon** [comment]
I will follow up on this on the upcoming days, looks like I have some homework to do :smile:

**Comment by tomwanzek** [comment]
Yeah I hadn't finished reviewing yet either. This one is more work since
the api docs seem to be work in progress.

I'll let you know as soon as I have chance to continue.

**Comment by Ledragon** [comment]
I updated the files according to the comments. The only remaining thing (besides tests _sigh_) i to allow for `{type: 'Sphere'}`in Spherical math function. I should be able to do this tomorrow.

I have to say, you must spend an incredible amount of time reading the actual code to catch all these things. I'm pretty impressed!

**Comment by tomwanzek** [comment]
Thanks for the changes. I will review asap. Just had to get some chores and bug fixes out of the way on the other modules.

**Comment by tomwanzek** [comment]
@Ledragon I will branch off the newly updated `d3-geo-finalization` branch with any suggested changes for your consideration. When I finish going through all your pain-staking work :smile:, I will create a PR for you to comment/thumb-up/thumb-down against.

**Pull request merged**
