### PR TITLE
d3-request finalization

### LINKED ISSUE #44: d3-request Definitions
Add Definitions for **d3-request** module.

Important: Under this milestone _Data Acquisition (Enhanced)_. The definitions should be structured as proper modules/UMD-style module definitions. I.e., they should be comparable to the modules tracked under milestone _Core Modules (Enhanced)_ and contained in the  master branch of this repo.

Combined with their tests, they should compile successfully using Typescript 2.0.0 (beta).

They should make use of function-context `this` typing, where appropriate, comparable to its use in under the _Core Modules (Enhanced)_ milestone.

For future consideration, `null` and `undefined` types should be used, where the API indicates the explicit types to be, e.g. for a function return type, `string | null` vs `string | undefined` vs. `string` only for non-nullable defined types.

Note, however, that, currently and in correspondence to the approach taken by **DefinitelyTyped/types-2.0** the compiler is using the `"strictNullChecks": false` option.

### LINKED ISSUE #45: d3-request Tests

### PR DESCRIPTION
**Pull request by tomwanzek**
@Ledragon can you please review and let me know, your take.

This PR completes the definitions and tests for d3-request. Fixes #44. Fixes #45. The one known follow-up would be adding in JSDoc comments to clarify the interaction between the callbacks for `on('load')`/`send`/`get`/`post` and the application of `response(...)` and `row(...)`.

### CODE REVIEW

**Comment by Ledragon** [comment]
Thanks for the update.
I find it better to use the `d3-dsv` types instead of a duplicated interface, but does referencing relative files like work when installing, i.e. will both get downloaded when installing using **@types**?

I was not aware of the new possible usage of `this` (I saw you mentioned it, but did not yet check it out), so I guess the changes in events callback make sense, while still keeping compatibility with previous way of doing things (see [here](https://github.com/Ledragon/MakeOverMonday30/blob/master/src/app.ts) for the way I tend to parse files using d3, and handle the data when parsing is complete; this still seems to work). Should tests be added to make sure callbacks using lambda expression still work?

Not much comment on the tests, they reflect the changes you made in types definitions.

I suggest you add yourself to the authors list as well, that seems only logical.

**Comment by tomwanzek** [comment]
Thanks for the review. Let's see:
- d3-dsv is a proper dependency of d3-request, so they will always be used together. So this one is a lot easier than the complications between d3-axis and d3-time, where that is not the case. (On a side note: there is some chatter on the TypeScript side related to _stripped down_ `package.json` files for the definitions itself, but I have not found a complete/proper write up last I looked. I will follow-up on that separately when I try to get more pick-up on **DefinitelyTyped/types-2.0** to address the open issues from that side of the eco system.
- `this` typing of function scope. I have added it together with the updated typing of the _data_ arguments in the callback/listeners, after digging through the code. The API doc is not very explicit on the matter. It would be worthwhile to circle back with Mike Bostock to possibly update the API docs. Did not have the time to do that yet...
- As for lambdas, they should not be used. This goes back to d3-dispatch which is used internally by d3-request. Like d3-selection and d3-transition, the argument needs to be a proper function, as the `this` context is bound internally by invoking it with `.call(...)`. That would not work correctly with a lambda, which is lexically scoped. See the section _Invoked through call or apply_ [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) . So unintended behaviors/errors may arise, which could be buried under the rug. (In some cases they may not surface, i.p. when not accessing the `this` context explicitly. It may also make a difference if your compilation target is still ES5 as opposed to ES6.)
- I'm not hung up on being added as an author, if someone else took the initiative to get the ball rolling on these definitions. If you prefer, I will do it though.

Let me know, if you are o.k. if I merge into `master`.

**Comment by Ledragon** [comment]
- Seems clear as for the dependencies between the modules
- Anyhow, what is done seems to work as expected
- I understand the concerns about the rescoping of `this`, but I personally never had to reuse the request itself once I get my data, so never had any trouble using a lambda for the callback. And I always circled around to avoid having to use `this`, even in events callback of selection (sometimes in an ugly way, such as `d3.select(d3.event.currentTarget)`). Being from a C# background, I find it hard to get my head around the change of meaning of `this`, so I prefer avoiding it (but that's totally personal)
- as you prefer for being mentioned as an author, I just think the amount of rework you did deserves it

Merging is ok for me, I guess we are clear on the questions.

**Comment by tomwanzek** [comment]
Thanks for the o.k. I added myself as a further author. Given the wide spread of D3,  I guess, the more maintainers the better in the long run. :sweat_smile:

**Pull request merged**
